### ISSUE TITLE
Executable commands in the bin directory instead of tmp

### ISSUE THREAD

**Issue by acabreragnz** [bixlabs/authentication#39]
I think `./bin` is a more appropiate directory to save the generated build (`make build`) than `./tmp`. If you read the [golang documentation](https://golang.org/doc/code.html#Workspaces) you could find that they use `./bin` directory to contain executable commands. I know that we are not working with workspaces but seems to be a guideline we could follow. Anyway this is issue is not much important and can be discussed.

**Comment by jac1013** [comment]
Closing this one as we are going to use `./bin` for executables that are required in development, build dist should still go to `./tmp` because they are not intended to be used as tools in `./bin`... examples of what goes in bin is the binary for the linter and the binary for creating swagger documentation.
